account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.redirect_login),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
]

inixindo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventori.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

        widgets = {
            'username': forms.TextInput(attrs={'type': 'text', 'class': 'input'}),
            'email': forms.TextInput(attrs={'type': 'email', 'class': 'input'}),
            'password': forms.TextInput(attrs={'type': 'password','class': 'input'}),
        }

account/views.py
from django.contrib.auth import authenticate, login as sign_in, logout as sign_out
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm


# def authenticated(request):
#     if request.user.is_authenticated:
#         return True
#     else:
#         return False


# Create your views here.
def redirect_login(request):
    return redirect('/account/login/')

def login(request):
    if request.method == "POST":
        accountID = request.POST['accountID']
        password = request.POST['password']
        user = authenticate(account_id=accountID, password=password)
        # user = authenticate(username=accountID, password=password)
        if user is not None:
            # messages.success(request, 'Login Success')
            sign_in(request, user)
            return redirect('inventori:index')
        else:
            messages.error(request, 'Login Gagal')
            return redirect('account:login')
        # return redirect_login(request)]
    return render(request, "page_login.html", {'formRegister': RegisterForm()})


def logout(request):
    sign_out(request)
    return redirect('account:login')


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.password = make_password(form.cleaned_data['password'])
            model.save()
            messages.success(request, 'Register Success.')
        else:
            return render(request, 'page_login.html', {'formRegister': form})

    return redirect("account:login")

account/templates/page_login.html
{% extends 'layout_auth.html' %}

{% block title %}
    Login
{% endblock title %}

{% block content %}
    <div class="login-wrap" style="margin-top: 150px">
    {% if messages %}
        <div class="alert alert-success">
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <div class="login-html">
        <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
        <input id="tab-2" type="radio" name="tab" class="for-pwd"><label for="tab-2" class="tab">Register</label>
        <div class="login-form">
            <div class="sign-in-htm">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="group">
                        <label for="user" class="label">Account ID</label>
                        <input id="user" name="accountID" type="text" class="input">
                    </div>
                    <div class="group">
                        <label for="pass" class="label">Password</label>
                        <input id="pass" type="password" name="password" class="input" data-type="password">
                    </div>
                    <div class="group">
                        <input type="submit" class="button" value="Sign In">
                    </div>
                </form>
                <div class="hr"></div>
            </div>
            <div class="for-pwd-htm">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <form action="{% url 'account:register' %}" method="post">
                    {% csrf_token %}
                    {% comment %}<div class="group">
						<label for="new_user" class="label">Username</label>
						<input name="new_user" type="text" class="input">
					</div>
					<div class="group">
						<label for="new_pass" class="label">Password</label>
						<input name="new_pass" type="password" class="input">
					</div>
                    <div class="group">
						<label for="new_pass" class="label">Conf Password</label>
						<input name="new_pass" type="password" class="input">
					</div>{% endcomment %}
                    {% for field in formRegister %}
                        {{ field.errors }}
                        <div class="group">
                            {#                        {{field.label_tag}}#}
                            <label for="{{ field.label }}" class="label">{{ field.label }}</label>
                            {{ field }}
                            {#                            <input name="{{field.name}}" type="text" class="input">#}
                        </div>
                    {% endfor %}

                    <div class="group">
                        <input type="submit" class="button" value="Register">
                    </div>
                </form>
                <div class="hr"></div>
            </div>
        </div>
    </div>
{% endblock content %}