account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.redirect_login),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
]

inixindo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventori.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout_auth.html
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}"/>
</head>
<body>
<div>
    {% block content %}{% endblock content %}

    {% block javascript %}{% endblock %}
</div>

</body>
</html>

templates/layout_default.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Django CRUD</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% url 'inventori:barang.show' as barang_url %}
            <li class="nav-item {% if request.get_full_path == barang_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'inventori:barang.show' %}">Barang</a>
            </li>
            {% url 'inventori:inv.show' as inv_url %}
            <li class="nav-item {% if request.get_full_path == inv_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'inventori:inv.show' %}">Inventaris</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <a href="{% url 'account:logout' %}" class="btn btn-outline-danger my-2 my-sm-0" type="submit">Logout</a>
        </form>
    </div>
</nav>

<div class="container" style="padding-top: 50px">
    {% block content %}

    {% endblock content %}
</div>

{% block javascript %}{% endblock %}
</body>
</html>