account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.redirect_login),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
]

inixindo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventori.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventori/urls.py
from django.urls import path
from . import views

app_name = 'inventori'
urlpatterns = [
    path('', views.redirect_barang, name="index"),
    path('barang/', views.barang_show, name="barang.show"),
    path('barang/add', views.barang_add, name="barang.add"),
    path('barang/delete/<int:id>', views.barang_delete, name="barang.del"),
    path('barang/edit/<int:id>', views.barang_edit, name="barang.edit"),
    path('inventori/', views.inv_show, name="inv.show"),
    path('inventori/add', views.inv_add, name="inv.add"),
    path('inventori/edit/<int:id>', views.inv_edit, name="inv.edit"),
    path('inventori/delete/<int:id>', views.inv_delete, name="inv.del"),
]

inventori/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Barang(models.Model):
    barang_id = models.AutoField(primary_key=True)
    barang_nama = models.CharField(max_length=255)
    barang_brand = models.CharField(max_length=255)
    barang_jenis = models.CharField(max_length=255)
    barang_spek = models.CharField(max_length=500)
    barang_image = models.ImageField(default='default.png')
    barang_created = models.DateTimeField(auto_now_add=True)
    barang_updated = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return "{} - {}".format(self.barang_nama, self.barang_brand)

class Inventaris(models.Model):
    INV_STATUS = [
        ('aktif', 'Aktif'),
        ('rusak', 'Rusak'),
        ('hilang', 'Hilang'),
        ('dilelang', 'Dilelang'),
    ]

    inv_id = models.AutoField(primary_key=True)
    inv_barang_id = models.ForeignKey(Barang, on_delete=models.CASCADE)
    inv_nomor = models.CharField(max_length=100)
    inv_pengadaan_petugas = models.CharField(max_length=255)
    inv_pengadaan_tgl = models.DateTimeField(blank=True, null=True)
    inv_pengadaan_harga = models.FloatField()
    inv_perbaikan_petugas = models.CharField(max_length=255)
    inv_perbaikan_tgl = models.DateTimeField(blank=True, null=True)
    inv_lokasi = models.CharField(max_length=255)
    inv_status = models.CharField(max_length=10, choices=INV_STATUS, default='aktif')

inventori/forms.py
from django import forms
from django.core.files.images import ImageFile
from django.core import validators
from .models import Barang, Inventaris


class BarangForm(forms.ModelForm):
    class Meta:
        model = Barang
        fields = ['barang_nama', 'barang_brand', 'barang_jenis', 'barang_spek', 'barang_image']
        labels = {
            'barang_nama': 'Nama Barang',
            'barang_brand': 'Penyedia Barang',
            'barang_jenis': 'Jenis Barang',
            'barang_spek': 'Spesifikasi Barang',
        }
        widgets = {
            'barang_nama': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'barang_brand': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'barang_jenis': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'barang_spek': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
        }

    def clean_barang_image(self):
        picture = self.cleaned_data.get("barang_image")
        if picture.size > 1000000:
            raise forms.ValidationError("Kegedean bosque !!!")
        return picture

class InvForm(forms.ModelForm):
    class Meta:
        model = Inventaris
        fields = ['inv_barang_id', 'inv_nomor', 'inv_pengadaan_petugas', 'inv_pengadaan_tgl', 'inv_pengadaan_harga',
                  'inv_perbaikan_petugas', 'inv_perbaikan_tgl', 'inv_lokasi', 'inv_status']
        labels = {
            'inv_barang_id': 'Barang',
            'inv_nomor': 'Nomor Inventaris',
            'inv_pengadaan_petugas': 'Nama Petugas',
            'inv_pengadaan_tgl': 'Tanggal Pengadaan',
            'inv_pengadaan_harga': 'Harga Saat Pengadaan',
            'inv_perbaikan_petugas': 'Petugas Perbaikan',
            'inv_perbaikan_tgl': 'Tanggal Perbaikan',
            'inv_lokasi': 'Lokasi Inventaris',
            'inv_status': 'Status Inventaris',
        }
        widgets = {
            'inv_barang_id': forms.Select(attrs={'class': 'form-control'}),
            'inv_nomor': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'inv_pengadaan_petugas': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'inv_pengadaan_tgl': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'inv_pengadaan_harga': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'inv_perbaikan_petugas': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'inv_perbaikan_tgl': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'inv_lokasi': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'inv_status': forms.Select(attrs={'class': 'form-control'}),
        }

inventori/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import BarangForm, InvForm
from .models import Barang, Inventaris


# Create your views here.
@login_required
def redirect_barang(request):
    return redirect("inventori:barang.show")


# ============================== HALAMAN BARANG
@login_required
def barang_show(request):
    data = Barang.objects.all()
    return render(request, "barang.html", {'datas': data})


@login_required
def barang_add(request):
    if request.method == 'POST':
        form = BarangForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Barang berhasil ditambahkan')
            return redirect('inventori:barang.show')
        else:
            messages.error(request, 'Terjadi Kesalahan')
    else:
        form = BarangForm()
    return render(request, "barang_add.html", {'form': form})


@login_required
def barang_edit(request, id):
    barang = Barang.objects.get(barang_id=id)
    form = BarangForm(request.POST, instance=barang)
    if form.is_valid():
        form.save()
        messages.success(request, 'Barang berhasil diperbarui')
        # return redirect("inventori:barang.edit", id=id)
        return redirect("inventori:barang.show")
    return render(request, "barang_edit.html", {'barang': barang})


@login_required
def barang_delete(request, id):
    barang = Barang.objects.get(barang_id=id)
    barang.delete()
    return redirect("inventori:barang.show")


# ============================== HALAMAN INVENTARIS
@login_required
def inv_show(request):
    data = Inventaris.objects.all()
    return render(request, "inventaris.html", {'datas': data})


@login_required
def inv_add(request):
    if request.method == 'POST':
        form = InvForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Barang berhasil ditambahkan')
            return redirect('inventori:inv.show')
        else:
            messages.error(request, 'Terjadi Kesalahan')
    else:
        form = InvForm()
        return render(request, "inventaris_add.html", {'form': form})


@login_required
def inv_edit(request, id):
    data = Inventaris.objects.get(inv_id=id)

    if request.method == 'POST':
        form = InvForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            messages.success(request, 'Inventaris berhasil diperbarui')
            # return redirect("inventori:barang.edit", id=id)
            return redirect("inventori:inv.show")
    else:
        form = InvForm(instance=data)
        return render(request, "inventaris_edit.html", {'data': data, 'form': form})


@login_required
def inv_delete(request, id):
    inventaris = Inventaris.objects.get(inv_id=id)
    inventaris.delete()
    return redirect("inventori:barang.show")

inventori/templates/barang.html
{% extends 'layout_default.html' %}
{% block title %} Barang {% endblock %}


{% block content %}
    <div style="text-align: center">
        <h3>DATA BARANG</h3>
    </div>
    {% if messages %}
        <div class="alert alert-info">
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <div style="padding-bottom: 10px">
        <a href="{% url 'inventori:barang.add' %}" class="btn btn-outline-success">Tambah</a>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>Nama</th>
            <th>Brand</th>
            <th>Jenis</th>
            <th>Spesifiaksi</th>
            <th>Aksi</th>
        </tr>
        </thead>
        <tbody>

        {% for d in datas %}
            <tr>
                <td>{{ d.barang_nama }}</td>
                <td>{{ d.barang_brand }}</td>
                <td>{{ d.barang_jenis }}</td>
                <td>{{ d.barang_spek }}</td>
                <td><img src="{{d.barang_image.url}}" alt="Gambar" style="width: 50px"></td>
                <td>
                    <a href="{% url 'inventori:barang.edit' d.barang_id %}" class="btn btn-outline-primary">Edit</a>
                    <button class="btn btn-outline-danger" onclick="delBarang({{ d.barang_id }})">Hapus</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block javascript %}
    <script>
        function delBarang(BarangID) {
            $.post(`/barang/delete/${BarangID}`, {'csrfmiddlewaretoken': '{{ csrf_token }}'})
                .then(response => {
                    location.reload()
                })
        }
    </script>
{% endblock %}

inventori/templates/barang_add.html
{% extends 'layout_default.html' %}
{% block title %} Tambah Barang {% endblock %}


{% block content %}
    <form action="{% url 'inventori:barang.add' %}" method="post" enctype="multipart/form-data">
        <div class="card">
            {% if messages %}
                <div class="alert alert-info">
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="card-body">
                <div style="text-align: center">
                    <h3>Tambah Barang</h3>
                </div>

                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.label }}" class="label">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                {% endfor %}

            </div>
            <div class="card-footer">
                <button class="btn btn-outline-success">Simpan</button>
            </div>
        </div>
    </form>
{% endblock %}

inventori/templates/barang_edit.html
{% extends 'layout_default.html' %}
{% block title %} Edit Barang {% endblock %}


{% block content %}
    <form action="{% url 'inventori:barang.edit' barang.barang_id %}" method="post">
        <div class="card">
            <div class="card-body">
                {% if messages %}
                    <div class="alert alert-info">
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div style="text-align: center">
                    <h3>Update Barang</h3>
                </div>
                {% csrf_token %}

                <div class="form-group">
                    <label for="Nama Barang" class="label">Nama Barang</label>
                    <input type="text" name="barang_nama" class="form-control" maxlength="255" required
                           id="id_barang_nama" value="{{ barang.barang_nama }}">

                </div>

                <div class="form-group">
                    <label for="Penyedia Barang" class="label">Penyedia Barang</label>
                    <input type="text" name="barang_brand" class="form-control" maxlength="255" required
                           id="id_barang_brand" value="{{ barang.barang_brand }}">

                </div>

                <div class="form-group">
                    <label for="Jenis Barang" class="label">Jenis Barang</label>
                    <input type="text" name="barang_jenis" class="form-control" maxlength="255" required
                           id="id_barang_jenis" value="{{ barang.barang_jenis }}">

                </div>

                <div class="form-group">
                    <label for="Spesifikasi Barang" class="label">Spesifikasi Barang</label>
                    <input type="text" name="barang_spek" class="form-control" maxlength="500" required
                           id="id_barang_spek" value="{{ barang.barang_spek }}">

                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-outline-success">Simpan</button>
            </div>
        </div>
    </form>
{% endblock %}

inventori/templates/inventaris.html
{% extends 'layout_default.html' %}
{% block title %} Inventaris {% endblock %}


{% block content %}
    <div style="text-align: center">
        <h3>DATA INVENTARIS</h3>
    </div>
    {% if messages %}
        <div class="alert alert-info">
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <div style="padding-bottom: 10px">
        <a href="{% url 'inventori:inv.add' %}" class="btn btn-outline-success">Tambah</a>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>Nama Barang</th>
            <th>No. Inventaris</th>
            <th>Tgl Beli</th>
            <th>Petugas Pengadaan</th>
            <th>Harga Pembelian</th>
            <th>Lokasi</th>
            <th>Tanggal Maintenance Terakhir</th>
            <th>Nama Petugas Maintenance</th>
            <th>Status Barang</th>
            <th>Aksi</th>
        </tr>
        </thead>
        <tbody>

        {% for d in datas %}
            <tr>
                <td>{{ d.inv_barang_id.barang_nama }}</td>
                <td>{{ d.inv_nomor }}</td>
                <td>{{ d.inv_pengadaan_tgl }}</td>
                <td>{{ d.inv_pengadaan_petugas }}</td>
                <td>{{ d.inv_pengadaan_harga }}</td>
                <td>{{ d.inv_lokasi }}</td>
                <td>{{ d.inv_perbaikan_tgl }}</td>
                <td>{{ d.inv_perbaikan_petugas }}</td>
                <td>{{ d.inv_status }}</td>
                <td>
                    <a href="{% url 'inventori:inv.edit' d.inv_id %}" class="btn btn-outline-primary btn-block">Edit</a>
                    <button class="btn btn-outline-danger btn-block" onclick="delInv({{ d.inv_id }})">Hapus</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block javascript %}
    <script>
        function delInv(invID) {
            $.post(`/inventori/delete/${invID}`, {'csrfmiddlewaretoken': '{{ csrf_token }}'})
                .then(response => {
                    location.reload()
                })
        }
    </script>
{% endblock %}

inventori/templates/inventaris_add.html
{% extends 'layout_default.html' %}
{% block title %} Tambah Inventaris {% endblock %}


{% block content %}
    <form action="{% url 'inventori:inv.add' %}" method="post">
        <div class="card">
            {% if messages %}
                <div class="alert alert-info">
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="card-body">
                <div style="text-align: center">
                    <h3>Tambah Inventaris</h3>
                </div>

                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.label }}" class="label">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                {% endfor %}

            </div>
            <div class="card-footer">
                <button class="btn btn-outline-success">Simpan</button>
            </div>
        </div>
    </form>
{% endblock %}

inventori/templates/inventaris_edit.html
{% extends 'layout_default.html' %}
{% block title %} Ubah Inventaris {% endblock %}


{% block content %}
    <form action="{% url 'inventori:inv.edit' data.inv_id %}" method="post">
        <div class="card">
            {% if messages %}
                <div class="alert alert-info">
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="card-body">
                <div style="text-align: center">
                    <h3>Tambah Inventaris</h3>
                </div>

                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.label }}" class="label">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                {% endfor %}

            </div>
            <div class="card-footer">
                <button class="btn btn-outline-success">Simpan</button>
            </div>
        </div>
    </form>
{% endblock %}